# Generated by Django 3.1.6 on 2021-02-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_ounty',
            new_name='default_county',
        ),
    ]
